/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as GameRouteImport } from './routes/game'
import { Route as NewsRouteImport } from './routes/news'
import { Route as OddsRouteImport } from './routes/odds'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as ApiAutoRecapRouteImport } from './routes/api/auto-recap'
import { Route as EditorBeatRouteImport } from './routes/editor_.beat'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as TeamsSlugRouteImport } from './routes/teams/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const OddsRoute = OddsRouteImport.update({
  id: '/odds',
  path: '/odds',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutoRecapRoute = ApiAutoRecapRouteImport.update({
  id: '/api/auto-recap',
  path: '/api/auto-recap',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorBeatRoute = EditorBeatRouteImport.update({
  id: '/editor_/beat',
  path: '/editor/beat',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsSlugRoute = TeamsSlugRouteImport.update({
  id: '/teams/$slug',
  path: '/teams/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/desk': typeof DeskRoute
  '/editor': typeof EditorRoute
  '/game': typeof GameRoute
  '/news': typeof NewsRoute
  '/odds': typeof OddsRoute
  '/standings': typeof StandingsRoute
  '/api/auto-recap': typeof ApiAutoRecapRoute
  '/editor/beat': typeof EditorBeatRoute
  '/teams/$slug': typeof TeamsSlugRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/desk': typeof DeskRoute
  '/editor': typeof EditorRoute
  '/game': typeof GameRoute
  '/news': typeof NewsRoute
  '/odds': typeof OddsRoute
  '/standings': typeof StandingsRoute
  '/api/auto-recap': typeof ApiAutoRecapRoute
  '/editor/beat': typeof EditorBeatRoute
  '/teams/$slug': typeof TeamsSlugRoute
  '/teams': typeof TeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/desk': typeof DeskRoute
  '/editor': typeof EditorRoute
  '/game': typeof GameRoute
  '/news': typeof NewsRoute
  '/odds': typeof OddsRoute
  '/standings': typeof StandingsRoute
  '/api/auto-recap': typeof ApiAutoRecapRoute
  '/editor_/beat': typeof EditorBeatRoute
  '/teams/$slug': typeof TeamsSlugRoute
  '/teams/': typeof TeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/desk'
    | '/editor'
    | '/game'
    | '/news'
    | '/odds'
    | '/standings'
    | '/api/auto-recap'
    | '/editor/beat'
    | '/teams/$slug'
    | '/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/desk'
    | '/editor'
    | '/game'
    | '/news'
    | '/odds'
    | '/standings'
    | '/api/auto-recap'
    | '/editor/beat'
    | '/teams/$slug'
    | '/teams'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/desk'
    | '/editor'
    | '/game'
    | '/news'
    | '/odds'
    | '/standings'
    | '/api/auto-recap'
    | '/editor_/beat'
    | '/teams/$slug'
    | '/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  DeskRoute: typeof DeskRoute
  EditorRoute: typeof EditorRoute
  GameRoute: typeof GameRoute
  NewsRoute: typeof NewsRoute
  OddsRoute: typeof OddsRoute
  StandingsRoute: typeof StandingsRoute
  ApiAutoRecapRoute: typeof ApiAutoRecapRoute
  EditorBeatRoute: typeof EditorBeatRoute
  TeamsSlugRoute: typeof TeamsSlugRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odds': {
      id: '/odds'
      path: '/odds'
      fullPath: '/odds'
      preLoaderRoute: typeof OddsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auto-recap': {
      id: '/api/auto-recap'
      path: '/api/auto-recap'
      fullPath: '/api/auto-recap'
      preLoaderRoute: typeof ApiAutoRecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor_/beat': {
      id: '/editor_/beat'
      path: '/editor/beat'
      fullPath: '/editor/beat'
      preLoaderRoute: typeof EditorBeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$slug': {
      id: '/teams/$slug'
      path: '/teams/$slug'
      fullPath: '/teams/$slug'
      preLoaderRoute: typeof TeamsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  DeskRoute: DeskRoute,
  EditorRoute: EditorRoute,
  GameRoute: GameRoute,
  NewsRoute: NewsRoute,
  OddsRoute: OddsRoute,
  StandingsRoute: StandingsRoute,
  ApiAutoRecapRoute: ApiAutoRecapRoute,
  EditorBeatRoute: EditorBeatRoute,
  TeamsSlugRoute: TeamsSlugRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
